### ISSUE TITLE
Feature Request: add build needed soft link files

### ISSUE THREAD

**Issue by leon0625** [amezin/vscode-linux-kernel#11]
When `code linux-3.17.28`, VS code loads all the kernel files (30000+).This will cause VS Code analysis to be slow, and there are many files in it that I don't care about, I only care about those files that are needed for compilation (6000+).
I think it is possible to create a folder outside the kernel (for example, linux-3.17.28-build-need) with soft links to the files needed for compilation. and then `code linux-3.17.28-build-need`. This will greatly shorten the time of vscode analysis

**Comment by amezin** [comment]
Hm. I thought it indexes only files that are referenced in `compile_commands.json`. Are you sure it loads sources not enabled in the configuration (i. e. is it slow if you `make allnoconfig && make && .vscode/generate_compdb.py` and then restart VSCode)?
